//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DesignYourselfEntities : DbContext
    {
        public DesignYourselfEntities()
            : base("name=DesignYourselfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SolvedTask> SolvedTask { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Task> Task { get; set; }
        public DbSet<TaskType> TaskType { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserType> UserType { get; set; }
    }
}
