//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.SolvedTask = new HashSet<SolvedTask>();
        }
    
        public int TaskId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TaskData { get; set; }
        public string StandartData { get; set; }
        public int UserId { get; set; }
        public int TaskTypeId { get; set; }
    
        public virtual ICollection<SolvedTask> SolvedTask { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual User User { get; set; }
    }
}
