//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskType
    {
        public TaskType()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int TaskTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Elements { get; set; }
    
        public virtual ICollection<Task> Task { get; set; }
    }
}
